// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/replenishcc-buy-cards/BuyCardsPreview.tsx": () => import("../components/mockups/replenishcc-buy-cards/BuyCardsPreview.tsx"),
  "./components/mockups/replenishcc-buy-cards/CardInfoCurrent.tsx": () => import("../components/mockups/replenishcc-buy-cards/CardInfoCurrent.tsx"),
  "./components/mockups/replenishcc-buy-cards/CardInfoReferenceMatch.tsx": () => import("../components/mockups/replenishcc-buy-cards/CardInfoReferenceMatch.tsx")
};
